### PR TITLE
Adds version check for grpc-web

### LINKED ISSUE #629: Add check for correct proto versions
We need to update the `grpc-web` version in these places:
- `dev/package.json`
- `public/package.json`
- `Makefile`

We currently support a workflow that allows to compile the proto files and UI frontend code using:
```sh
% make proto
% make ui
```

As part of this workflow, we should add a check to ensure that all versions are updated before compiling the UI.

Unfortunately, it doesn't appear that `protoc-gen-grpc-web` has a `-v` or `--version` flag that can be checked.

We should also check these versions:
```sh
% protoc --version
libprotoc 3.19.4
% protoc-gen-go --version
protoc-gen-go v1.27.1
% protoc-gen-go-grpc --version
protoc-gen-go-grpc 1.2.0
% protoc-gen-grpc-web --version
protoc-gen-grpc-web: Unknown option: --version
```

### PR DESCRIPTION
**Pull request by meling**
- Added proto_path options to settings.json
- Added grpcweb version check before the ui target
- Added check for latest release version of grpc-web
- Added alternative install instructions for grpc-web

Fixes #629

### CODE REVIEW

**Comment by meling** [comment]
@JosteinLindhom @0xf8f8ff @oleespe @Synnems @Padogen Could you all try out this PR on your local machine to see if there are any problems? The main thing to try is to run `make version-check`, and if that works it would be interesting to see if `make proto` works. I think this should work on Windows WSL, but probably not on pure Windows PowerShell, but feel free to let me know if it actually works. It is not a goal to make it work under Windows, but it should work under WSL.

The goal of this PR is to check that the locally installed dev tools you are using is of the correct version.

PS: If you have a newer version of some of these dev tools, then it should not give a warning, but should compile new versions of the `.pb.go` files... essentially forcing others to upgrade.

**Comment by JosteinLindhom** [comment]
Both `make version-check` and `make proto` work on WSL.

In Windows `make version-check` (and ` go run .\cmd\vercheck\main.go`)  fails due to `protoc-gen-go.exe` not having any arguments `--version`, or other variants to show version.

```ps
PS quickfeed> protoc-gen-go --version
protoc-gen-go.exe: unknown argument "--version" (this program should be run by protoc, not directly)
```

I have not been able to find a solution for this issue however.

**Comment by meling** [comment]
Ok. That's interesting. Then either you have an old version installed, or it is from another codebase than [this one](https://github.com/protocolbuffers/protobuf-go/blob/master/cmd/protoc-gen-go/main.go). It looks like you can download the latest windows version from [here](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.28.0). Although, I typically use `make devtools`, that should do the same.

Note that we haven't upgraded to the latest version; maybe I'll do that as part of this PR.

**Comment by meling** [comment]
Could you try to add this code to the `vercheck` tool on after Line 53:
```go
	if strings.Contains(s, `unknown argument "--version"`) {
		log.Println(s)
		log.Fatalf("Your installed %s version is too old. Please update to the latest version.", tool)
	}
```

**Comment by meling** [comment]
The previous code probably didn't work; @JosteinLindhom could you try with the new version. Feel free to play around with the vercheck code.

**Comment by JosteinLindhom** [comment]
I did indeed have an older version where the `--version` flag was not implemented. Updating to the one you linked works.

Looking for `unknown argument "--version"` does not seem to work, as `sh.Output(tool + "--version")` returns an empty string, with an error `exit status 1`.

**Comment by meling** [comment]
It is often a bit confusing where errors are being sent. I have updated again. @JosteinLindhom does this version work better?

**Comment by JosteinLindhom** [comment]
The lastest commit fixed the issue I had in Windows.

**Pull request merged**
